[theme]
# Primary accent color for interactive elements.
primaryColor = "#d33682"

# Background color for the main content area.
backgroundColor = "#A47F59"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#918578"

# Color used for almost all text.
textColor = "#fff"
